_BASE_: "./base.yaml"

# base settings
output_dir: './_runs/'  
base_model: "layoutLMv3"
exp_name: "layoutLMv3_finetune_IGN"
embedding_components: ["token"]
aux_losses: ["bidirection", "focal"]
padding_token_id: -100
mask_token_id: -1
max_len: 32

poly_only: False
text_only: False
fuse: "sum"

layoutLMv3_pretrained_weights: null #"/home/yijun/work/MapText/text_linking/_weights/pretrain_layoutLMv3/model_epoch_4800.pth"
poly_pretrained_weights: null

batch_size: 2
# train_datasets: ["MapText_train"]
train_datasets: ["IGN_train"]
train_data_probabilities: [1]
# val_dataset: "MapText_val"
val_dataset: "IGN_val"
val_data_shuffle: False

save_every_epoch: 100
eval_every_epoch: 1
num_epochs: 100
lr: 0.00005
weight_decay: 0.0

version: 0



