_BASE_: "./base.yaml"

# base settings
output_dir: './_runs/'
base_model: "light"
exp_name: 'test'
embedding_components: ["token", "poly"]
aux_losses: ["bidirection", "focal"]

token_padding_max_length: 1000
padding_token_id: -100
mask_token_id: -1
max_len: 32

poly_only: False
text_only: False

light_pretrained_weights: "_weights/pretrain_light/model_epoch_3000.pth"
# light_pretrained_weights: "_runs/test__v3/models/model_epoch_1.pth"

batch_size: 2
train_datasets: ["MapText_train"]
train_data_probabilities: [1]
val_dataset: "MapText_val"
val_data_shuffle: False

save_every_epoch: 100
eval_every_epoch: 1
num_epochs: 100
lr: 0.00005
weight_decay: 0.0
scheduler_patience: 5
patience: 9

version: 4

