_BASE_: "./base.yaml"

# base settings
output_dir: './_runs/'  
exp_name: 'poly_only'
embedding_components: ["poly"]
aux_losses: ["focal", "bidirection"]

padding_token_id: -100
mask_token_id: -1
max_len: 32

poly_only: False
text_only: False

poly_pretrained_weights: "_weights/pretrain_poly/model_epoch_3000.pth"

train_datasets: ["MapText_train"]
train_data_probabilities: [1]
val_dataset: "MapText_val"
val_data_shuffle: False

save_every_epoch: 100
eval_every_epoch: 1
num_epochs: 100
lr: 0.00005
weight_decay: 0.0

version: 0

