# base settings
output_dir: './_runs/'  

# model settings
exp_name: "layoutLMv3_pretrain"
base_model: "layoutLMv3"
pretrained_model_name: "microsoft/layoutlmv3-base"
resume: False
checkpoint_path: ""

# add_poly: True
add_wpa_loss: True
token_padding_max_length: 512
max_position_embeddings: 1024
poly_pretrained_weights: null

# training settings
batch_size: 2
num_epochs: 5000
lr: 0.00005
eval_every_epoch: 10
save_every_epoch: 200
warmup_ratio: 0.
weight_decay: 0.01

# Device configuration
device: "cuda"

# Distributed training parameters
distributed: True
world_size: 1
local-rank: 0
dist_on_itp: False
dist_url: "env://"

version: 0