# base settings
output_dir: './_runs/'  

# model settings
exp_name: "test"
base_model: "light"
pretrained_model_name: "microsoft/layoutlmv3-base"
resume: False
checkpoint_path: ""

# add_poly: True
add_wpa_loss: True
token_padding_max_length: 512
max_position_embeddings: 1024
padding_token_id: -100
mask_token_id: -1
max_len: 32
poly_pretrained_weights: "./_weights/pretrain_poly/model_epoch_3000.pth"

# dataset settings
train_datasets: ["MapText_json_train"] #, "Rumsey1_train", "Rumsey2_train"]

# training settings
batch_size: 2
num_epochs: 3000
lr: 0.00005
num_samples_per_epoch: 200
eval_every_epoch: 10
save_every_epoch: 1
warmup_ratio: 0.048
weight_decay: 0.01

# Device configuration
device: "cuda"

# Distributed training parameters
distributed: True
world_size: 1
local-rank: 0
dist_on_itp: False
dist_url: "env://"

version: 3
